/**
 * ResearchClaw — Research Module Types
 *
 * Defines the data structures used throughout the agentic research pipeline:
 * survey → idea analysis → idea selection → structured report.
 */

/** A single academic paper reference retrieved during survey. */
export type PaperReference = {
  /** Unique identifier (arXiv ID, DOI, or semantic scholar ID). */
  id: string;
  title: string;
  authors: string[];
  year: number;
  abstract: string;
  /** Source where this paper was found. */
  source: "arxiv" | "semantic_scholar" | "web";
  url: string;
  /** Which paper section(s) this reference is relevant to. */
  sections?: string[];
  /** Short annotation explaining relevance to the research goal. */
  annotation?: string;
};

/** A candidate research idea extracted from the survey. */
export type ResearchIdea = {
  id: string;
  title: string;
  description: string;
  /** Why this idea is novel compared to existing work. */
  novelty: string;
  /** Estimated difficulty: low | medium | high */
  difficulty: "low" | "medium" | "high";
  /** Estimated impact if successful. */
  potentialImpact: string;
  /** Related paper IDs that support or motivate this idea. */
  relatedPapers: string[];
};

/** The final selected research idea with acceptance criteria. */
export type SelectedIdea = ResearchIdea & {
  /** High-level acceptance criteria for the overall research goal. */
  acceptanceCriteria: AcceptanceCriterion[];
};

/** A single acceptance criterion for the research goal. */
export type AcceptanceCriterion = {
  id: string;
  description: string;
  /** How to measure success: e.g. "+2 BLEU points on benchmark X" */
  metric?: string;
  /** Whether this criterion is mandatory or optional. */
  required: boolean;
};

/** The complete survey report produced by the research agent. */
export type SurveyReport = {
  /** The original research goal provided by the user. */
  researchGoal: string;
  /** ISO timestamp when the survey was completed. */
  completedAt: string;
  /** Summary of the current state of the field. */
  fieldSummary: string;
  /** Key challenges and open problems identified. */
  openProblems: string[];
  /** All retrieved paper references. */
  papers: PaperReference[];
  /** Candidate ideas generated from the survey. */
  ideas: ResearchIdea[];
  /** The selected idea to pursue. */
  selectedIdea: SelectedIdea;
  /** References organized by paper section for writing guidance. */
  referencesBySection: Record<string, PaperReference[]>;
};

/** Serializable state persisted to disk between pipeline stages. */
export type ResearchState = {
  version: "1";
  researchGoal: string;
  workspaceDir: string;
  surveyReport?: SurveyReport;
  todoList?: TodoList;
  experimentResults?: ExperimentResult[];
  paperDraft?: PaperDraft;
  status: ResearchStatus;
  updatedAt: string;
};

export type ResearchStatus =
  | "init"
  | "surveying"
  | "planning"
  | "executing"
  | "reviewing"
  | "writing"
  | "compiling"
  | "done";

/** A single task in the experiment To-do list. */
export type TodoTask = {
  id: string;
  title: string;
  description: string;
  /** High-level acceptance criteria for this specific task. */
  acceptanceCriteria: string;
  status: "pending" | "in_progress" | "done" | "failed";
  /** Results written by the executor after completion. */
  result?: string;
  /** Absolute path to the result file written to disk. */
  resultFile?: string;
  createdAt: string;
  completedAt?: string;
};

/** The experiment To-do list generated by the planner. */
export type TodoList = {
  researchGoal: string;
  selectedIdeaTitle: string;
  /** Overall acceptance criteria (from selected idea). */
  overallAcceptanceCriteria: AcceptanceCriterion[];
  tasks: TodoTask[];
  createdAt: string;
  updatedAt: string;
};

/** Result of a single experiment task execution. */
export type ExperimentResult = {
  taskId: string;
  taskTitle: string;
  summary: string;
  /** Key findings from this experiment. */
  findings: string[];
  /** Metrics measured (name → value). */
  metrics?: Record<string, string | number>;
  /** Absolute path to the detailed result file. */
  resultFile: string;
  completedAt: string;
};

/** The paper draft produced by the writing agent. */
export type PaperDraft = {
  title: string;
  abstract: string;
  /** LaTeX source file path. */
  latexFile: string;
  /** Compiled PDF file path. */
  pdfFile?: string;
  sections: PaperSection[];
  createdAt: string;
};

/** A single section in the paper. */
export type PaperSection = {
  name: string;
  title: string;
  /** Reference IDs cited in this section. */
  citations: string[];
};
